apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-checker
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: health-checker
  template:
    metadata:
      labels:
        app: health-checker
    spec:
      containers:
        - name: health-checker
          image: {{ .Values.healthChecker.image }}
          envFrom:
            - secretRef:
                name: health-checker-secret