apiVersion: v1
kind: Secret
metadata:
  name: dns-api-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  SUPABASE_URL: {{ .Values.api.secrets.SUPABASE_URL | quote }}
  SUPABASE_KEY: {{ .Values.api.secrets.SUPABASE_KEY | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: health-checker-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.healthChecker.secrets.DATABASE_URL | quote }}