apiVersion: v1

kind: Service

metadata:
  name: {{ include "charts.fullname" . }}

spec:

  type: {{ .Values.service.type }}

  selector:
    app: zonal-cache

  ports:

  - port: {{ .Values.service.port }}

    targetPort: 8080

    protocol: TCP