apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: apache-ingress
  namespace: {{ .Values.global.namespacePrivado }}
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "10"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /Apache1(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: proyecto-apache1
                port:
                  number: 80
          - path: /Apache2(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: proyecto-apache2
                port:
                  number: 80