replicaCount: 1

image:
  repository: cortes64/ui
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  targetPort: 80
  nodePort: 30080

env:
  apiUrl: "http://zonal-cache-service:8080"
