FROM httpd:2.4

COPY index.html /usr/local/apache2/htdocs/index.html
COPY style.css /usr/local/apache2/htdocs/style.css

EXPOSE 80

#http://apache-server-service/
#http://apache-server-service/style.css