apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-ui
  labels:
    app: ui
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http-tcp
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          env:
            - name: VITE_API_URL
              value: {{ .Values.env.apiUrl | quote }}
